triggers added

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -26,21 +26,13 @@ workflows:
           inputs:
           - project_location: "$PROJECT_LOCATION"
           - module: "$MODULE"
-          - variant: "$VARIANT"
-      - android-unit-test@1:
+          - variant: release
+      - gradle-runner@1:
           inputs:
-          - project_location: "$PROJECT_LOCATION"
-          - module: "$MODULE"
-          - variant: "$VARIANT"
-      - android-build@0:
-          inputs:
-          - project_location: "$PROJECT_LOCATION"
-          - module: "$MODULE"
-          - variant: "$VARIANT"
-      - sign-apk@1:
-          run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
+          - gradle_task: assembleRelease assembleAndroidTest
+          - gradlew_path: "$PROJECT_LOCATION/gradlew"
       - deploy-to-bitrise-io@1: {}
-      - cache-push@2: {}
+        - cache-push@2: {}
   primary:
     steps:
     - activate-ssh-key@4:
@@ -49,6 +41,36 @@ workflows:
     - cache-pull@2: {}
     - script@1:
         title: Do anything with Script step
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            flavor="Debug"
+            testFlavor=""
+            if [[ $BITRISE_GIT_BRANCH =~ 'feature/release' ]]; then
+                echo "Triggered on release branch, building release flavor"
+                flavor="Release"
+                testFlavor=""
+            else
+                echo "Triggered on non-release branch, building debug flavor"
+                flavor="Debug"
+                testFlavor=$flavor
+            fi
+
+            echo "ANDROID_FLAVOR: ${flavor}"
+            echo "ANDROID_TEST_FLAVOR: ${testFlavor}"
+
+            envman add --key ANDROID_FLAVOR --value "$flavor"
+            envman add --key ANDROID_TEST_FLAVOR --value "$testFlavor"
+
+            # or run a script from your repository, like:
+            # bash ./path/to/script.sh
+            # not just bash, e.g.:
+            # ruby ./path/to/script.rb
     - install-missing-android-tools@2:
         inputs:
         - gradlew_path: "$PROJECT_LOCATION/gradlew"
